M48
; DRILL file {KiCad (6.0.4)} date Fri Oct 14 21:12:54 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-14T21:12:54-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X3.135Y-2.6067
X3.1358Y-5.5201
X4.2382Y-2.6067
X8.1752Y-4.1224
X8.1752Y-5.5201
T0
M30
