M48
; DRILL file {KiCad (6.0.4)} date Fri Oct 14 21:25:16 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-14T21:25:16-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X5.2835Y-2.6764
X5.2835Y-4.8811
X6.8976Y-2.6764
X6.8976Y-4.8811
T0
M30
